### ISSUE TITLE
Ledger Sync Window

### ISSUE THREAD

**Issue by dkm412** [ccwalletio/tracker#1]
while connecting the ledger and if waiting for commands, there is a loading screen.
> i think it would be good if on that screen there would be a message like "please check your ledger and allow the commands...."

**Comment by Scitz0** [comment]
There is a notice before you click next/confirm with instructions. But we can add the same information to the loading screen to make it clearer.

**Comment by Scitz0** [comment]
To be included in an upcoming release, closing issue.
