### ISSUE TITLE
update of Cardano app for Ledger

### ISSUE THREAD

**Issue by janmazak** [ccwalletio/tracker#102]
There is a new version of Cardano Ledger app with Plutus support under review, and an accompanying update of Ledgerjs is also available (see the pre-release below).
https://github.com/LedgerHQ/app-cardano/pull/18/files
https://github.com/vacuumlabs/ledgerjs-cardano-shelley/releases/tag/v5.0.0-rc1

**Comment by Scitz0** [comment]
thanks for the heads up

**Comment by janmazak** [comment]
I've made a mistake and forgot some commits, here they are:
https://github.com/vacuumlabs/ledgerjs-cardano-shelley/releases/tag/v5.0.0-rc2

**Comment by janmazak** [comment]
The npm release is now available:
https://www.npmjs.com/package/@cardano-foundation/ledgerjs-hw-app-cardano
(small API changes since rc2 and rc4)

Ledger will release the new Cardano app (v4.0.0) sometimes the next week. In experimental mode in LedgerLive, it is available on provider 4.

**Comment by mezuny** [comment]
Hi @janmazak, thanks for the suggestions! We're a bit behind on replying to all issues on the Github here, but are ready to support 4.0.0!
