### ISSUE TITLE
Request: Save ADAHandle in Adressbook

### ISSUE THREAD

**Issue by Entspanndi** [ccwalletio/tracker#103]
This is my favourite wallet on Cardano. Many thanks for the development and constant improvement. 

Would it be possible to store not only addresses in the address book but also ADAHandles? So that one does not have to enter the handle but can select a saved handle.

**Comment by mezuny** [comment]
Hey @Entspanndi, happy to hear you're enjoying Eternl! This functionality will be included in our next release. Thanks for the suggestion!
