### ISSUE TITLE
Transaction History: Minus Sign at Fractional Part of Native Tokens

### ISSUE THREAD

**Issue by HeptaSean** [ccwalletio/tracker#105]
When a native asset is sent out by a transaction, there is a second minus sign before the fractional part of the amount:
![screenshot-2022-03-18-14:06:21](https://user-images.githubusercontent.com/1820735/159008610-82a8948a-3a2b-48c2-8efb-deb93ee4f1be.png)

Maybe, the code can be refactored to use the same functionality as for ADA/Lovelace. Should be the same calculations.

(This is in browser extension 1.5.3.)

**Comment by mezuny** [comment]
Hey @HeptaSean, we are aware that this is still in and will work to resolve this for the next release. Thank you for the (big amounts) of feedback. It hasn't gone unnoticed! 😄

**Comment by HeptaSean** [comment]
This is fixed. Probably already some time ago.
