### ISSUE TITLE
Feature Request: Display JSON from Cardano Token Registry

### ISSUE THREAD

**Issue by HeptaSean** [ccwalletio/tracker#107]
It's totally awesome that you can view the CIP 25 metadata for NFTs in ccvault.

Since you also display metadata from the Cardano Token Registry in the Token List, you query it, anyway.

Could that be shown as its JSON source next to the CIP 25? That way, we could easily see, where the user-friendly presentation comes from, if they use both (in slight abuse of the standards), …

**Comment by mezuny** [comment]
Hey @HeptaSean, we are currently working on a token view overhaul which will include way more information visualized. I believe this might be similar to what you're suggesting here! 😄

**Comment by HeptaSean** [comment]
Looking back at this after some months.

The new (not so new anymore) token view *is* nice.

But it does not really address, what I wrote above.

If a token is an NFT (or misuses the on-chain CIP 25 metadata for an FT), you show the metadata as raw JSON. I can see, where the attributes came from.

But if it uses the Cardano Token Registry, the source of those metadata is not shown. Could you also show the raw JSON of the registry metadata? Perhaps even with a link to the registry Github?

**Comment by Scitz0** [comment]
Hi, shouldn't be a problem to add a raw json field for token registry metadata just like for NFT metadata. Link to GitHub would not be possible as we have it setup right now. I'll add it as an internal feature request for team members to look into.

**Comment by Scitz0** [comment]
I'm actually closing this again as it doesn't add any value. This due to a couple of reasons.

1. Token metadata registry entries are validated before merged(or should be). So only contains entries that are valid.
2. The fields in the TMR are fixed, and we display them if available. Decimals etc are not displayed but can be seen in the amount at the top.
