### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by gldtn** [ccwalletio/tracker#110]
Can we get a Firefox extension please? So many wallet leaves out Firefox, and so many people dislike Chrome/Chromium.

Thanks!

**Comment by MarekPasnikowski** [comment]
I refuse to use Chrome. Please rethink this monopolistic decision.

**Comment by mezuny** [comment]
Hey guys, we used to have a Firefox extension, but it got removed by Firefox. Their stance is they'll only allow it when they get both a compiled build and all source code, which for now is the reason it isn't available on the Firefox store

**Comment by melroy89** [comment]
Damn, I gonna hate Firefox more and more by the day.
