### ISSUE TITLE
Feature Request: Allow search by asset fingerprint

### ISSUE THREAD

**Issue by docter-tirrud** [ccwalletio/tracker#112]
Currently in Eternl for Chrome 1.5.5 there exists the ability to Filter the transaction list by message, tx id, or an UTxO address:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/92059696/161435032-a55566a7-c7d7-41e8-baa7-0f7e768af389.png">

It would be useful to be able to filter on the asset fingerprint:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/92059696/161435131-5d753619-6590-4b68-a210-5d92168a8877.png">

It would make it much easier to answer the question "How did I get THIS token, when, and for how much?" without having to scroll through all the transactions.

I would make the same request for the CSV download file--add a column to identify **which**  token was included in the transaction. Right now, as far as I can see, the TxType indicates "Received Ada and Tokens" but the asset fingerprint or token name are not included.

**Comment by marcuspuchalla** [comment]
Thanks for the suggestion. We have planned this feature and will start working on it shortly.
We'll let you know in which release it will be included.

**Comment by marcuspuchalla** [comment]
Dear @docter-tirrud ,

we implemented the change regarding searching for asset fingerprint.
Exporting of the fingerprint in a CSV export is not yet planned but we will put this in List of requested changes. 
Therefore I'll now close this ticket.

If it does not work for you feel free to open it again or create a new one.

Best Marcus
