### ISSUE TITLE
Withdraw Rewards Text

### ISSUE THREAD

**Issue by grepeverything** [ccwalletio/tracker#113]
The text for the Withdraw Rewards section is misleading.

Your rewards are automatically part of your delegated stake. There is no need to withdraw rewards other than sending them away.

I believe rewards are not included when one is voting. This would be a good reason to withdraw them as well.

**Comment by marcuspuchalla** [comment]
Thank you very much for your comment.

You are correct; voting power only considers the balance in UTxOs. So the rewards will not count towards that voting power.

We will adjust the text, taking this fact into account.

**Comment by marcuspuchalla** [comment]
We adjusted this part of the text to include the information about the voting.
Thanks again for the help!
