### ISSUE TITLE
Feature Request: Export Transaction History CSV in local timezone

### ISSUE THREAD

**Issue by bmelville** [ccwalletio/tracker#118]
When viewing transaction history in the app, transactions are shown in local time. However, when exporting transactions to CSV, they are exported in UTC.

It would be helpful to be able to export transactions in the same timezone they are shown in the main app, especially for use in other applications where it is imperative to maintain timezone consistency across transactions from different wallets.

**Comment by marcuspuchalla** [comment]
Hello @bmelville, Thanks you for reaching out. 
We added this feature request to our backlog and will implement it as soon as possible.
We'll let you know when it is released in here!

best regards, Marcus

**Comment by marcuspuchalla** [comment]
With the release of version 1.9.2, you can export the history in local time.
There is an option on the dialog, see here:
 
<img width="615" alt="Bildschirmfoto 2022-09-15 um 16 28 40" src="https://user-images.githubusercontent.com/89977979/190430593-7bdcf8cd-5f6b-4e67-85a1-f85bd4c1fd8f.png">
