### ISSUE TITLE
Eternl addon content script failing to load csl-v10.0.4.wasm on all web pages

### ISSUE THREAD

**Issue by refi93** [ccwalletio/tracker#119]
Hi, it seems a recent update of eternl addon resulted in the content script loading `csl-v10.0.4.wasm` from a relative path which e.g. for https://www.amazon.com/ obviously doesn't exist and results in a failed fetch request being logged in the console or even an unhandled exception, depending on the way the host website handles unknown paths:

```
Uncaught (in promise) CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
```

To reproduce it, just install latest eternl addon, try visiting pretty much any webpage and the error should appear in the console

**Comment by marcuspuchalla** [comment]
Thank you for reporting that issue.
We will have a look and make sure this will be fixed asap.

**Comment by chriswill** [comment]
This was a real pain.  I'm a web developer and all of a sudden *my app* started throwing unhandled exceptions, because I had the Eternl extension turned on and that request fires on all browser requests, even if you aren't using Eternl at the time.

Had to disable the extension.

**Comment by tomas1433** [comment]
@chriswill  did you found out how to disable   Eternl wallet extension, i am in the same situation ...

**Comment by tomas1433** [comment]
ok i got it disabling the extensions on chrome... what a mess lol

**Comment by marcuspuchalla** [comment]
Hello @refi93 
We fixed this in one of the last versions. Sorry that we did not reach out earlier.

If you still have problems, please try to update to the latest extension.

Feel free to open this again if you still have problems.

Best Marcus
