### ISSUE TITLE
2FA security for wallet login / spending

### ISSUE THREAD

**Issue by gitmachtl** [ccwalletio/tracker#12]
would be a great separation from the currently available wallets if the users can use 2FA to log into the ccwallet and/or also for spending. this would also give the opportunity to have multiple users using the same computer (mainuser, brother, wife, husband, kids...) all with there own 2FA.

**Comment by gitmachtl** [comment]
this feature also drastically improves the privacy issue

**Comment by Scitz0** [comment]
The idea is to add a pin wallet locking feature in addition to the spending password that will lock the wallet and hide the amount.

**Comment by gitmachtl** [comment]
My suggestion would be to use TOTP and Yubikey identification for the "login" and also for the spending password. People are used to that workflow nowadays for all the exchanges and online platforms.

**Comment by marcuspuchalla** [comment]
We had a look at this issue again and decided not to implement it yet but leave it in our backlog.

2FA done right is a client-server solution, and we cannot store/sync user data on our servers right now. We don't have the capacity for this and want to concentrate on giving a flawless wallet syncing a higher priority.
 
TOTP and YubiKey would require us to send data between client and server for every login.

For now, you can have some strong security if you use the wallet with a ledger and a spending password per wallet. This way, you have the added ledger security, the password on your ledger, and the password for spending.
