### ISSUE TITLE
eternl defaulting to mainnet after update

### ISSUE THREAD

**Issue by thisHermit** [ccwalletio/tracker#120]
I am unable to use my testnet wallet to connect to testnet dapps as it defaults to mainnet instead of testnet.

**Comment by marcuspuchalla** [comment]
Can you please try again using the latest browser extension and let me know if it worked ?
I just tested it and it works fine here.

Please first switch to Testnet, then open a DApp Browser Testnet app and try again.

**Comment by thisHermit** [comment]
Sorry for not updating this sooner. It works fine now.
