### ISSUE TITLE
Ledger nano secondary market problems in the cardano ecosystem

### ISSUE THREAD

**Issue by Gaaarz** [ccwalletio/tracker#123]
Hello,

I love your wallet. I have several issues with the combination of a Ledger Nano X. If I try to sign data:

![image](https://user-images.githubusercontent.com/102361550/172116454-8417ffb4-0b0c-45b3-97a8-d189b4bee564.png)

I will get: 

![image](https://user-images.githubusercontent.com/102361550/172116506-30df545b-3a23-4da7-86f0-0d0f72a5fc53.png)

Also if I want to buy on the secondary market like jpg.store I get an error with a missing witness address and can´t confirm the transaction with my ledger.

Regards

**Comment by Scitz0** [comment]
Hi, ledger doesn't support arbitrary data signing yet. Please use a regular mnemonic wallet for this. 

Regarding jpg.store issue, please describe a bit more what the actual issue is.

**Comment by Gaaarz** [comment]
Thank you for clarification. The jpg.store issue resolved itself. In the past when I tried to buy something on jpg.store the wallet said that a witness address is missing. Think this is fixed in the meantime. Thank you!
