### ISSUE TITLE
Be more vocal about CCWallet not being OSS and why.

### ISSUE THREAD

**Issue by adamczykm** [ccwalletio/tracker#125]
A crypto wallet is one thing that has full control over your private keys. If you have strong reasons for obfuscating its source code, you should be more vocal about them and educate your users about risks and their source of trust.

**Comment by mezuny** [comment]
Hey Adam,

There are several aspects to this topic.
1) We are a very small team and are trying to create an income from the hard work we put into Eternl.
2) If we'd open source the code a larger company with a marketing team could easily rip us off.
3) With the code being open source we would see dozens of scammer sites trying to steal peoples phrases, much more convincing then it is today.

We started building this wallet to be able to better manage our funds. And we build trust with the community. That's basically all we can do at this point.

Larger holding should also be on a hardware wallet, which won't ever leak private keys and verify transaction contents. We are considering an audit once we have released Eternl v2 (if financially possibly, as those are far from cheap). It wouldn't make sense to have one done currently, as we hope to release v2 (which is a complete overhaul) in the coming 6 months.
