### ISSUE TITLE
An earlier request for how do I rename a wallet/sub-account is marked as completed. How?

### ISSUE THREAD

**Issue by jtmoderate876** [ccwalletio/tracker#126]
How do I rename wallet/sub-account?

**Comment by HeptaSean** [comment]
You can rename a wallet in Settings → Name and Password.

Accounts do not have names that can be set in Eternl.

**Comment by Scitz0** [comment]
We will redesign version 2 of Eternl to allow for account naming. The flow of wallet/accounts will change a bit. But this is on the horizon so for the near term, you will have to settle for wallet name. 

Be assured that the request is not forgotten or ignored. Lets keep this issue open for now to let users know its handled and added to todo.

**Comment by marcuspuchalla** [comment]
With the release of version 1.9.2, you can now name your accounts.
For a complete change list, see https://twitter.com/eternlwallet/status/1570340765179715586
