### ISSUE TITLE
Cardano Testnet support.

### ISSUE THREAD

**Issue by SevenbitsShubham** [ccwalletio/tracker#127]
After connecting to the Cardano Testnet it is showing 'status: no connection'. Is Eternl/ccWallet  is not supporting Cardano  testnet. Or is there any other way to  connect Caradno Testnet.

**Comment by mezuny** [comment]
Hi @SevenbitsShubham, thanks for reaching out. Which of the testnets were/are you trying to use? We support both the pre-production and preview testnets that are newly released after the 'old' testnet was discontinued

**Comment by marcuspuchalla** [comment]
The new test networks should all work fine. As @mezuny said we support both new networks.
If you still have some connection errors please let us know.
