### ISSUE TITLE
Tokens should display their value in selected currency

### ISSUE THREAD

**Issue by knasiotis** [ccwalletio/tracker#129]
I have some SUNDAE in my wallet let's say. Why not implement a feature that shows how much they're worth in €?

**Comment by Scitz0** [comment]
Thanks for the suggestion but we already have this implemented in dev branch. Will soon make it into a release I think. Watch out for some nice updates on this area in the upcoming release(s).

**Comment by marcuspuchalla** [comment]
@knasiotis as of today, with release 1.9.2 you can see the token value when you open the token detail view.
The value will be displayed in the currency you have configured under "App Preferences" -> "Currency and Regional Options"

<img width="356" alt="Bildschirmfoto 2022-09-15 um 17 00 23" src="https://user-images.githubusercontent.com/89977979/190438243-d41f144f-e282-4c35-a065-4d4e300092a4.png">
