### ISSUE TITLE
Eternl extension conflict with the site miro.com

### ISSUE THREAD

**Issue by allenyllee** [ccwalletio/tracker#130]
If I enable Eternl extension (version 1.9.0) in Brave (Chromium 104.0.5112.102), and go to the miro site:
https://miro.com/app/dashboard/
the screen will keep loading forever;
<img width="960" alt="Snipaste_2022-08-24_20-17-30" src="https://user-images.githubusercontent.com/3991134/186416259-dcc86bfd-8c65-4c40-9338-e8cbb2e973b4.png">

However, if I disable Eternl, the site will back to normal:
<img width="960" alt="Snipaste_2022-08-24_20-19-23" src="https://user-images.githubusercontent.com/3991134/186416594-a5c0055d-2a2c-49e1-9d24-20744ce52202.png">

**Comment by marcuspuchalla** [comment]
Thank you for the report. We are currently investigating and will come back to this issue soon.

**Comment by marcuspuchalla** [comment]
We looked into this issue, and there is, unfortunately, nothing we can do on our side to fix this problem. 

Our recommended fix is to deactivate the plugin when using this site. Deactivating will not affect the wallets you have in the app. You might also create another profile for using this site where you do not install our extension.
