### ISSUE TITLE
Connect v9 integration

### ISSUE THREAD

**Issue by Hannsek** [ccwalletio/tracker#133]
Hello ccwallet team!

I am writing you from Trezor company with a message that we released new version of Connect. It is v9 and is now GA. You can find it here: https://www.npmjs.com/package/@trezor/connect/v/9.0.0

If you have any questions or want to report a problem, feel free to reach us.

**Comment by Scitz0** [comment]
Hi, thank you for the information. 

Its on the top of the list to get implemented when we come home from our community event trip over to the US. So you can expect it to be implemented within a few weeks.

**Comment by Hannsek** [comment]
Hello,thank you very much for the response.Enjoy the trip. Jan Šetina732 50 37 5313. 10. 2022 v 22:49, Ola [AHLNET] ***@***.***>:﻿
Hi, thank you for the information.
Its on the top of the list to get implemented when we come home from our community event trip over to the US. So you can expect it to be implemented within a few weeks.

**Comment by sime** [comment]
I believe Eternl wallet is updated to Trezor Connect v9. https://twitter.com/eternlwallet/status/1599471748482990080

Also tested the webapp myself and it opened connect.trezor.io/9

**Comment by Scitz0** [comment]
> I believe Eternl wallet is updated to Trezor Connect v9. https://twitter.com/eternlwallet/status/1599471748482990080
> 
> Also tested the webapp myself and it opened connect.trezor.io/9

Thats correct 😄, thanks will close this issue.
