### ISSUE TITLE
Feature Request: Support for image metadata split into array on Tokens List page

### ISSUE THREAD

**Issue by perplexusdev** [ccwalletio/tracker#137]
IPFS Content Identifier v1 is 66 bytes in length, so it must be split into an array when used in cardano metadata to avoid the <=64 bytes per line constraint.
When this technique is used for the "image" attribute of NFT metadata (following https://cips.cardano.org/cips/cip25/), the metadata will not be read properly by Eternl and the image will not display in the Account/Tokens List page.

**Comment by perplexuslabs** [comment]
IPFS Content Identifier v1 is 66 bytes in length, so it must be split into an array when used in cardano metadata to avoid the <=64 bytes per line constraint.
When this technique is used for the "image" attribute of metadata (following https://cips.cardano.org/cips/cip25/), the metadata will not be read properly by Eternl and the image will not display in the Account/Tokens List page.

**Comment by MarcelKlammer** [comment]
Please provide a reference token / metadata we can take a look at.

**Comment by perplexusdev** [comment]
<img width="468" alt="image" src="https://user-images.githubusercontent.com/115051045/205163635-fd97390f-e587-4268-bd7a-445fb2431df2.png">

Test 6 uses IPFS CID v1 in the image attribute. It is an array of two strings, per https://cips.cardano.org/cips/cip25/. It would not display properly in eternl.

Test 7 uses IPFS CID v0 in the image attribute. It is just a string.

The following screenshot is from CIP25
<img width="664" alt="image" src="https://user-images.githubusercontent.com/115051045/205164272-6e3f066d-ccc1-489b-8ffa-4a9d6a6b5605.png">

The image value may be a URI (string) or an array

**Comment by Scitz0** [comment]
Since version 1.9.8 we load images from external CDN as primary source. If this fails we fall back to own parsing. And to me the parsing looks correct. If the content of image fields is an array its joined into a single string.
