### ISSUE TITLE
Rewards export function

### ISSUE THREAD

**Issue by gitmachtl** [ccwalletio/tracker#14]
A function to export all the rewards from epoch x->y, maybe in a .csv and/or .json format. Maybe also with the currently price at that timestamp?

**Comment by TheStophe** [comment]
Hopefully per wallet and account too, .csv preferred, do python analysis on it!

**Comment by marcuspuchalla** [comment]
We have this on our backlog list and will implement this in the following months.

**Comment by marcuspuchalla** [comment]
Also see: https://github.com/ccwalletio/tracker/issues/33

**Comment by mezuny** [comment]
Hi guys, we have a basic export functionality available at this point and will expand on it in the future. Thanks for the suggestions!
