### ISSUE TITLE
Eternl crashes with Error code: Out of Memory, during initialization

### ISSUE THREAD

**Issue by thaebler** [ccwalletio/tracker#155]
I cannot open Eternl Chrome Extension anymore because it crashes during the initial load with 'Out of Memory'

I've configured several Wallets in it

Is there a way I can give the extension more memory?

**Comment by Scitz0** [comment]
Please remove the Eternl extension and then re-add it. This should clear storage. Then please only add back necessary wallets for now and wait for 1.11 version of Eternl. This will include a complete re-write of storage and sync with a greatly improved memory footprint.
