### ISSUE TITLE
FR: Allow selecting of tokens to send from the overview screen

### ISSUE THREAD

**Issue by Crypto2099** [ccwalletio/tracker#16]
Just a thought on a quality of life improvement. When reviewing a large-scale NFT/Token collection, give a checkbox or similar to select multiple tokens to send that will auto-populate the "send" transaction screen with the tokens already selected (we can still choose quantities from the send screen to keep things streamlined).

**Comment by Scitz0** [comment]
Implemented and deployed with 1.0.2 release.
