### ISSUE TITLE
cosmetics/add features - nice to have

### ISSUE THREAD

**Issue by defender2803** [ccwalletio/tracker#18]
More things I looked at.

When looking at the stake pools you can copy the address...can you put a button to go to a pool site such as adastat.net or pool.pm? Some use a little box with an arrow or maybe some other link type gizmo icon.

Saturation bar has red, orange, and green
Pledge bar has green, orange, and blue
Think pledge bar should have blue and two other colors...not hot pink preferably...thinking a purple and brown/black?
Differentiate the bars a bit.
Both bars are in ADA so the ADA symbol...move to end of string of numbers and values so it is there once? Doesn't look as crowded.
Saturation bar: 5m A (1%) -> 5m (1%) A
Pledge bar: 5m A (5m A) -> 5m (5m) A

I take it the two numbers on the pledge bar are pledged amount and actual pledge...can you do a mouse over help bubble to explain it?

Everything is in millions so when low numbers it gets pretty down there... .001m. Can we get k under 1m? Is that already in works?

**Comment by Scitz0** [comment]
Thanks for the suggestions. As I found all of your requested changes valid I think I got them all included. Should be available shortly.
