### ISSUE TITLE
FR: Add Ability to Send Multiple UTXO in a Single Transaction

### ISSUE THREAD

**Issue by Crypto2099** [ccwalletio/tracker#2]
TYPE: Feature Request

One critical piece that I feel all Cardano wallets currently lack is the ability to send multiple UTXO in a single transaction.

I would love to have the ability to "build" a transaction by adding multiple receive addresses and building unique token bundles (Ada and/or optionally native assets) to be sent. Particularly as we start to see novel native asset utility it may become necessary to send a token(s) along with a specified amount of Ada to an address (SC or not) in order to trigger a specific effect.

A good example of this is the Time Trotters "merge" functionality where a user must send the tokens as well as a payment to a specified address. Let's hypothetically say that I have 5 Time Trotters and want to perform 2 merges which would require me to send two of my trotters + 50 Ada to an address in order to burn those two and create a new merged NFT. If I could add both token bundles as discrete UTXO in a single transaction we can limit the overall number of transactions and thereby fees necessary.

Following the same logic above, I should be able to send multiple UTXO to the same or different addresses, with each token bundle creating a new, unique UTXO (whether it is the same address or different addresses). This can be very helpful for things like token distribution (i.e. I want to send all of my CryptoKnitties to a wallet and have them all live on the same UTXO, then create another UTXO to contain my Time Trotters tokens).

**Comment by Scitz0** [comment]
Implemented and deployed
