### ISSUE TITLE
Brave SHIELDS

### ISSUE THREAD

**Issue by nicolasayotte** [ccwalletio/tracker#20]
Wallet updating does not currently work if the Brave SHIELDS is on with those settings:
![image](https://user-images.githubusercontent.com/7725061/128035178-cf4880b4-f051-424a-a6ea-a30594a07e65.png)

 I need to turn it off for the ccwallet app site for sync to work.

**Comment by ccwalletio** [comment]
Thanks for the info. We will take a look.

**Comment by Scitz0** [comment]
I'm unable to confirm this issue.
Closing for now but please comment if it's still an issue.

![image](https://user-images.githubusercontent.com/15903629/141615060-f01f83ae-906a-4e9a-b67b-aeb2c0cddf60.png)
