### ISSUE TITLE
Multi asset and multi address transaction

### ISSUE THREAD

**Issue by kawanua-pool** [ccwalletio/tracker#21]
My suggestion is to made this wallet that can sent more than one native token to more than one wallet address. This will be cool!

**Comment by ccwalletio** [comment]
An advanced tx builder is on our list. Thanks for the suggestion.

**Comment by cardano-apexpool** [comment]
I have the same suggestion.
Please also include the option to withdraw rewards in any transaction, not only when this is required.

**Comment by marcuspuchalla** [comment]
Minor update: We still have the advanced tx builder on our list. We'll start working on it in the following months.
