### ISSUE TITLE
Feature request: Multiple Accounts

### ISSUE THREAD

**Issue by rknightion** [ccwalletio/tracker#22]
This wallet is off to an awesome start, and I'm finding it a pleasure to use compared to my usual routine.
However, the one request I have for the roadmap is multiple accounts. Adalite currently has this (https://adalite.medium.com/multi-account-support-and-partial-delegation-fd96aa793f9d), and as the SPO ecosystem grows with more innovative things such as ISOs, delegators are likely to want to split up their stake without using a different wallet/using the same seed.
I know Yori and Daedalus have said they'll implement this at some point in the future, so getting there first might be one way to attract additional users (although I appreciate that this may not be easy, even though I believe it is part of the standard).

**Comment by Scitz0** [comment]
Implemented and live.
