### ISSUE TITLE
Add a "Send Another" Button to the Sending Screen

### ISSUE THREAD

**Issue by Crypto2099** [ccwalletio/tracker#3]
Once successfully submitting a transaction one needs to refresh the window or go to another "tab" (i.e. Summary, Transactions, etc) in order to refresh the "Send" form and send a new transaction. Currently, clicking on the "Send" tab simply leaves you at the transaction confirmation.

I think making either/both: Clicking the "Send" tab takes you back to the "New Send" form and/or adding a "New Transaction" button to the transaction confirmation interface will increase the usability of the UX.

![image](https://user-images.githubusercontent.com/63186174/123684535-720e3500-d802-11eb-852d-56f82bb001eb.png)

**Comment by Scitz0** [comment]
Solved by transferring the user to the transactions page after successful submission. In case of error, a retry button is added that takes you back to confirm page. Waiting to close until fully implemented.

**Comment by ccwalletio** [comment]
Once a tx was submitted and it pending the UI switches to the transaction list.
