### ISSUE TITLE
Feature Request: Compact Send View

### ISSUE THREAD

**Issue by pmcl77** [ccwalletio/tracker#30]
I would like to see an option of a compact "1-page view" for sending ADA/Tokens, instead of having to go through multiple pages to send. 

This page should include:
- Send-to Addr
- Amount ADA / Add Tokens
- Message
- Spending Password

If it would get too cramped, I could see the summary, spending password and confirm button on a separate page.

Thanks and keep up the good work!

**Comment by Scitz0** [comment]
As a follow-up on this issue, what benefit would this single page send page give?
I don't currently see the issue with clicking next a few times to complete the steps. If it's about speed surely there can't be much of a difference?

**Comment by marcuspuchalla** [comment]
With version 1.4, we reduced the steps to send a transaction. The page where you input a message is now optional. 

For now, we do not plan to make a "1-page view" as you suggested. However, this may change in the future when there is more need for this.
