### ISSUE TITLE
FR: Editable pool explorer link in pool section

### ISSUE THREAD

**Issue by cardanians** [ccwalletio/tracker#32]
I like using ccwallet, but I would really like to be able to link to adapools.org in the pool overview, or some native explorer options. Actually is here only crdanoscan.

**Comment by marcuspuchalla** [comment]
You can now set an explorer for different link types in the global settings. Adapool is also available as an option.

Therefore we close this issue.
 
<img width="637" alt="Bildschirmfoto 2022-01-24 um 12 47 07" src="https://user-images.githubusercontent.com/89977979/150777707-155d3ab5-4d2c-42ae-bda6-89a4ebdfc0e7.png">
