### ISSUE TITLE
Feature Request: Export Transactions to CSV (including NFT Data)

### ISSUE THREAD

**Issue by pmcl77** [ccwalletio/tracker#33]
It would be great to see an export function, to export all transactions into a csv file. Espacially including Data on Tokens/NFTs.

My goal is to housekeep my purchases and sales of NFTs. 

So basically it would be great to have a list which besides the basic transaction data includes info on:
- Token Name
- Token Fingerprint
- Pool.pm URL
- Token Price (if it can be determined)

I understand it might be difficult to "map" sending ADA transactions to receiving Token transactions, especially if there is more than one token received.

Maybe that will change with Smart Contracts and make something like this easier?

**Comment by Scitz0** [comment]
Similar FR to #14.

**Comment by marcuspuchalla** [comment]
We linked this issue in our internal backlog and will return to it as soon as we implement export functions, which are on our list for the following months.

**Comment by mezuny** [comment]
Hi @pmcl77, support for this has been added in a basic form, we will expand on it in the future, but this requires additional work. It is on our radar to do so, so we'll close this issue for now.
