### ISSUE TITLE
Feature Request: Transaction List for All/Multiple Wallets

### ISSUE THREAD

**Issue by pmcl77** [ccwalletio/tracker#34]
I would love to see a transaction list for all or selected (by a filter option) wallets.

**Comment by ccwalletio** [comment]
Do you mean a combined tx list of all open wallets?

**Comment by pmcl77** [comment]
Yes, exactly... There could maybe be an option to filter for certain wallets or wallet groups.

**Comment by mezuny** [comment]
Hi @pmcl77, we're considering adding 'overview' pages in the future, but this is far up the backlog. Thank you for the suggestion
