### ISSUE TITLE
Confusing chrome-extension popup using Firefox and a Ledger wallet

### ISSUE THREAD

**Issue by wout** [ccwalletio/tracker#36]
Today I made my first payment with ccwallet and I love it. There's only this rather confusing popup:

![image](https://user-images.githubusercontent.com/107324/136749352-737b0da1-a7c4-48b4-8376-005d501dfffc.png)

It's totally unnecessary because it can be ignored while using the Ledger wallet.

I'm using Firefox 93.0 on elementary OS 6.0 (based on Ubuntu 20.04) and a Ledger Nano S.

**Comment by MarcelKlammer** [comment]
I've no idea where this is coming from.

My guess: you have a link type setting, that opens that popup.

Never seen this before.

**Comment by wout** [comment]
Me neither :joy: . It's only with ccwallet. Adalite and Yoroi don't show this popup. It's also only with Firefox, in Brave and Chromium it's working fine. Looking at the configured protocol handlers in Firefox I can't see anything unusual.

Is there anything I can do to debug this?

**Comment by Scitz0** [comment]
Could you try overriding Ledger Transport and see if it makes a difference? WebUSB is the default choice in ccvault.io 
Other than this suggestion, I don't know what could cause it. Bust must be local to your browser, plugin conflict etc.

Closing for now as I haven't seen any progress in a while. Please comment here anyway and if its needed I will re-open issue.
