### ISSUE TITLE
BUG--Safari tries to create new passwords

### ISSUE THREAD

**Issue by Awashbu12** [ccwalletio/tracker#39]
On iPhone every time I get to the password screen iPhone thinks I want to make a new and puts up the recommended password thing.. can you fix the password screen to get the browser to recognize it is a password input and not a create? I've attached a photo showing what I mean. 
![image](https://user-images.githubusercontent.com/90179060/138324467-e5917272-e17f-4a50-a224-78123888c5b7.png)

**Comment by Scitz0** [comment]
Please follow this guide to disable:
https://apple.stackexchange.com/questions/305374/disable-safari-autofill-for-one-website

Password input handling is up to the client browser and not the serving website.
