### ISSUE TITLE
Feature Request: IPhone and Android mobile app

### ISSUE THREAD

**Issue by santonode** [ccwalletio/tracker#40]
Feature Request: will there ever be a mobile app version?

**Comment by Scitz0** [comment]
Thanks, a mobile app is something we have talked about but will not be implemented in the near future. So for now please use the browser on your mobile device. A timeline for this can't be set at this point.

**Comment by marcuspuchalla** [comment]
There are now iOS and Android apps available. Please note that they currently do not offer a dApp connector.
You can find the links on our official Linktree here: https://linktr.ee/ccvaultio
