### ISSUE TITLE
Update of ledgerjs

### ISSUE THREAD

**Issue by janmazak** [ccwalletio/tracker#41]
Hi, the Cardano Ledger app has an upcoming update (v.3.0.0) to support script elements in transactions, native scripts and multisig (see CIP 1854). The changes in transaction signing are breaking because stake credentials with script hashes are allowed now.  The corresponding ledgerjs update v4.0.0 also comes with some breaking changes in the API:
https://github.com/vacuumlabs/ledgerjs-cardano-shelley/releases/tag/v4.0.0-multisig-rc5
Ledgerjs v4.0.0 is compatible with older Ledger app versions.

Also, CBOR canonical ordering of map keys is now enforced in the new Ledger app, in compliance with CIP 21 (https://cips.cardano.org/cips/cip21/).

You have to upgrade to this new version of ledgerjs --- otherwise your users won't be able to sign any transactions with Ledger app 3.0.0.

**Comment by janmazak** [comment]
Ledgerjs v4.0.0 is ready:
https://github.com/cardano-foundation/ledgerjs-hw-app-cardano/releases/tag/v4.0.0

**Comment by janmazak** [comment]
Also available via npm:
https://www.npmjs.com/package/@cardano-foundation/ledgerjs-hw-app-cardano

**Comment by Scitz0** [comment]
Thanks for the heads-up. Made it more evident as Cardano app 3.0.0 was released to some customers through ledger live over a week ago but now pulled again it seems.

**Comment by Scitz0** [comment]
@janmazak Seems cardano-serialization-lib is not fully compatible with this upgrade. Detailed in this issue I just opened:
https://github.com/Emurgo/cardano-serialization-lib/issues/240

**Comment by Scitz0** [comment]
ccvault.io should be fully compatible with the upcoming 3.0.0 Ledger Cardano App. Closing this issue.
