### ISSUE TITLE
Feature Request: manual UTXO selection in transactions

### ISSUE THREAD

**Issue by adavibesp** [ccwalletio/tracker#42]
Hey CCWallet.

Cool feature would be to manually be able to select UTXO's to use when creating a transaction.
Could integrate with your current flow where at the end, the user can override utxo selection.

Regards,
Michael F, ADAVibe SPO

**Comment by cardano-apexpool** [comment]
Hello,

Same request from me. There are some tokens that people do not want to move from a specific address for different reasons, and the wallet selects them, even if there is only 1.5 ADA on that UTxO.
And another option could be a checkbox to automatically withdraw the rewards in the same transaction. 

Best regards,
George, APEX Pool.

**Comment by Scitz0** [comment]
We have a manual tx builder in the backlog that would let you select inputs and build the tx as desired. So this has been thought of before. But rest assured it is not forgotten.

**Comment by brouwerQ** [comment]
I really want this feature too!

**Comment by marcuspuchalla** [comment]
This feature is now available in Eternl using our TxBuilder.
Under "UTxO Input(s)" you can select the UTxOs you want to use for use in the transaction.
