### ISSUE TITLE
Feature Request: add Epoch transition dates/times

### ISSUE THREAD

**Issue by stakehodlers** [ccwalletio/tracker#46]
A small change that would be incredibly helpful would be to put the transition date (UTC would probably be easiest) next to/below each of the three Epoch's shown in the Current/Upcoming Delegations section.  Take a look at the Upcoming Rewards section of any Cardano wallet within Yoroi for a good example.  This is probably an easy add and is incredibly handy.  Thank you for your consideration and great work thus far!  Exceptional wallet that your team has created!

**Comment by Scitz0** [comment]
Added in latest release.
