### ISSUE TITLE
Improvements for the wallet

### ISSUE THREAD

**Issue by pajaroverde** [ccwalletio/tracker#48]
good afternoon, I would like to propose some improvements for your wallet.
As you know there are initiatives such as cardwallet that intends to use debit cards to spend the coins in the wallet. This represents an advantage and also a problem due to the KYC identification processes. That is why I think that a solution could be to pass our cryptocoins to fiat and then be able to fill or load a prepaid card with a pin.
This card is nameless and can be spent anonymously. You could even earn money by issuing the physical cards, in addition to charging a small commission per load.
I think this could keep the privacy of people who want to spend their crypto anonymously after transferring it to fiat inside the wallet.
Please tell me what you think of the idea.

**Comment by Scitz0** [comment]
Thanks for the suggestion. I can't speak for long time plans as we are a small team currently. But I don't see us adding something like this in the short or mid-term. But all ideas are good and you never know, we might be there one day going over added GH feature request and are in a better position to look into fiat on-ramp and specifically what you were asking about.
