### ISSUE TITLE
Feature Request: Support for multiple Trezor passphrase identified wallets

### ISSUE THREAD

**Issue by codefly** [ccwalletio/tracker#49]
It looks like you are caching the passphrase for the Trezor wallet, (which is great and convenient) however when I want to pair an additional wallet with the same device, identified by a different passphrase, I'm not prompted for the passphrase, instead I'm redirected to my existing wallet and told that a wallet already exists with this id.

Ideally when adding a new wallet I'm asked for the passphrase again and I can create an additional wallet.

Keep up the good work, great wallet!

**Comment by Scitz0** [comment]
I'm myself a Trezor with passphrase user so I know what you are talking about. It's however handled by trezor-connect, an external lib. I don't think there is much we can do about it, but I will check to make sure. The way you have to do it is to disconnect it from the computer in between to reset the connection.

**Comment by Scitz0** [comment]
Closing this issue as passphrase handling is handled by the Trezor Connect module. Better to open an issue on the TC GH page if this is still an issue. https://github.com/trezor/connect
