### ISSUE TITLE
Sometimes Fee Calculation Does Not Trigger

### ISSUE THREAD

**Issue by Crypto2099** [ccwalletio/tracker#5]
It seems like sometimes the wallet does not trigger the "Calculate Fee" portion and so no fees are shown/calculated when building a new send transaction. This disables the "next" button and makes it impossible to proceed with building the transaction. I have not tested exhaustively but it seems like once a specific amount of Ada creates this "lock up" condition, no amount of deleting/changing back to that specific value will force a fee calculation (although changing to a different value does work).

![image](https://user-images.githubusercontent.com/63186174/123685006-04163d80-d803-11eb-97b2-fedf3bfb2a3d.png)

**Comment by ccwalletio** [comment]
Added some more debugging console.logs. It's not really reproducable even if I have it sometimes as well.

**Comment by Scitz0** [comment]
We have identified a couple of issues related to this and fixed some. But a re-write of wallet switching logic needs to be completed before we can continue to verify if this is fully solved or not.

**Comment by MarcelKlammer** [comment]
Should be gone. Please test a bit more.
