### ISSUE TITLE
Feature Request: Send to other accounts option

### ISSUE THREAD

**Issue by 4bra** [ccwalletio/tracker#52]
Request to add pull down for sending to other accounts within my vault. Including accounts with my current wallet but also any accounts in my other wallets, all connected to CCVault. This concept comes from Metamask sending. 
Thank you

**Comment by marcuspuchalla** [comment]
As of now, you can quickly select an account of the current wallet under "Inter-Account Transaction" when building a send transaction. See here:

<img width="794" alt="Bildschirmfoto 2022-01-24 um 13 29 53" src="https://user-images.githubusercontent.com/89977979/150783287-cfeb0aaa-a4d6-4bac-9711-8b274168f93c.png">

But we also added the feature request to do this with different wallets to our backlog.

**Comment by mezuny** [comment]
We have added this functionality in our most recent release. If you have any feedback, do please let us know!
