### ISSUE TITLE
Feature Request  - Send Page

### ISSUE THREAD

**Issue by Edward212121** [ccwalletio/tracker#54]
When sending ada/token, is it possible to put all the fields in 1 page, like all the necessary information is on the front page, and not have to click next?

this will make it faster to send ADA to an NFT drop address for example  :)

thanks

![image](https://user-images.githubusercontent.com/96036571/145752533-35fc948e-f758-4da0-8282-128c037d6b11.png)

**Comment by marcuspuchalla** [comment]
A feature request for this already exists, but we decided not to implement it but put it in our backlog for now. 
Here is the original issue: https://github.com/ccwalletio/tracker/issues/30
