### ISSUE TITLE
Show the delegation change for delegation change transactions

### ISSUE THREAD

**Issue by timing** [ccwalletio/tracker#56]
Transactions that change the delegation do not look as such, it just looks like a regular transaction of 2 ADA and a 0.17 ADA fee. This means that a phisher could make a web-based delegation button that sends 2 ADA to another wallet address, and users then think this is fine. Also if the transaction popup confirms the transaction is a delegation change, the user might experience more trust with the website that implemented the button. 

It would be great if ccvault would show something like: "This transaction will change your delegation from MELD7 to ECO".

**Comment by ccwalletio** [comment]
Agreed, we plan to overhaul the Transaction preview and Send page completely.

Thanks for your suggestion.

**Comment by marcuspuchalla** [comment]
We show a badge for this which should make it more clear that the delegation is going to be changed.
Feel free to comment if you have any more suggestions on that topic. Thanks again for the suggestion.


<img width="252" alt="Bildschirmfoto 2022-04-20 um 12 44 15" src="https://user-images.githubusercontent.com/89977979/164214533-4911151b-a626-473e-972e-cbf424feff49.png">
