### ISSUE TITLE
Enhancement Request: Expanded Address Book Entries By Default

### ISSUE THREAD

**Issue by gibsonmedia247** [ccwalletio/tracker#57]
![Screen Shot 2021-12-25 at 7 58 19 AM](https://user-images.githubusercontent.com/96659438/147388885-f5a1541c-8bb5-4623-a965-98b5c79b814d.png)

Would be nice when sending, to have address book entries expanded by default. Maybe this could be a feature that can be toggled on/off in settings. For large amounts of address book entries, I am not sure how this could be handled. Maybe only show the top 10 or so entries?

**Comment by mezuny** [comment]
@gibsonmedia247 Thanks for the suggestion! We are currently overhauling the address book which will now be enabled by default. If you have any specific suggestions after we release 1.6.3, please let us know!

**Comment by Scitz0** [comment]
As mentioned this now works a bit differently. Address input step on send page has seen some big changes in 1.6.3. If you press address book it will now open in a modal to not clutter the main UI. The input box also now supports autocomplete and is my preferred way to access entries in the address book.
