### ISSUE TITLE
Enhancement Request: Send Tab > Enable Keyboard Return Entry for Default Selected Keys

### ISSUE THREAD

**Issue by gibsonmedia247** [ccwalletio/tracker#58]
Send Tab
- Receive Address > Next (would like to have Next button enabled for Keyboard Return entry)
- Message (would like to have Skip button enabled for Keyboard Return entry)
- Assets (Next is already enabled for Return entry, although I noticed when clicking on Back from the following screen, it no longer seems to work)
- Spending Password > Sign (Sign is already enabled)

**Comment by MarcelKlammer** [comment]
Hitting return when a valid address was entered will go to the next step. Am I missing something?
Message: Hit Tab (to focus the input field) > Hit Enter
