### ISSUE TITLE
Tracking staking rewards for tax purposes

### ISSUE THREAD

**Issue by MadOrkestra** [ccwalletio/tracker#59]
Hey there,

probably coming in your accounting solution at some point anyways, but I'll just leave this here: It'd be nice to have a feature to export staking rewards with their respective $ADA value in FIAT at the time the reward was paid out like https://pooltool.io/ does.

Lookings forward to things to come, thanks!

**Comment by mezuny** [comment]
Hi @MadOrkestra, thanks for reaching out, this for now should be available in basic form in our export as csv functionality.
