### ISSUE TITLE
Deleting Ada Value in Send Transaction Creates Weird Cursor Placement

### ISSUE THREAD

**Issue by Crypto2099** [ccwalletio/tracker#6]
Currently, after a min value is calculated for a transaction or you type in a custom amount and then delete it the Ada amount input resets to 0.000000 with the cursor by default at the far left of the input. This causes unexpected behavior when you click into the input and begin typing as whatever amount you type is appended to have an extra zero on the end (i.e. attempting to send 50 Ada all of a sudden becomes 500 Ada). This could create a major issue for users who are not paying close attention and/or are maybe in a rush (i.e. the stress/pressure of an NFT drop or other limited-time-window situation).

![image](https://user-images.githubusercontent.com/63186174/123685373-771fb400-d803-11eb-9c44-6040afa73126.png)

**Comment by ccwalletio** [comment]
Fixed that one. Input field is now actually emptied and one the background placeholder remains.
