### ISSUE TITLE
Feature request: Add abillity to send multiple UTxO's to different addresses in one transaction

### ISSUE THREAD

**Issue by eddex** [ccwalletio/tracker#60]
I would like to be able to send ADA to multiple addresses in one single transaction.

Example:
- I have 10 ADA in `wallet A`.
- I want to send 5 ADA to `wallet B` and 5 ADA to `wallet C`.
- Instead of creating one transaction to send 5 ADA from `wallet A` to `wallet B` and one transaction to send 5 ADA from `wallet A` to `wallet C` (paying transaction fees for both), I'd like to create one transaction that sends 5 ADA from `wallet A` to `wallet B` AND 5 ADA from `wallet A` to `wallet C`.

**Comment by marcuspuchalla** [comment]
We already plan to rework the transaction building process. This is one feature we will include.
