### ISSUE TITLE
Question: Why is ccvault not open source?

### ISSUE THREAD

**Issue by eddex** [ccwalletio/tracker#61]
It would really make me a lot more confident in using ccvault if the code would be open source. In the current state we are forced to blindly trust the creators not to steal our funds. This is far from ideal.

**Comment by nicolaskeller** [comment]
As much as I like the project and communication from the devs has been top notch in the past (thank you very much for your work!), I have to agree that it's very hard to trust a third party wallet that isn't (completely) open source.

**Comment by woodkm** [comment]
I love ccwallet. But I do agree here, it would be in ccvault's and the user's benefit to opensource the code.

**Comment by domib97** [comment]
I also like the fact that ccvault has the most options and shows important data but if you would ask Charles, he is also strictly against closed source. Yeah the algorithm that combines the utxos might be difficult but it should not be IP!

**Comment by mezuny** [comment]
Why the wallet is not Open Source?

There are several aspects to this topic.
1) We are a very small team and are trying to create an income from the hard work we put into Eternl.
2) If we'd open source the code a larger company with a marketing team could easily rip us off.
3) With the code being open source we would see dozens of scammer sites trying to steal peoples phrases, much more convincing then it is today.

We started building this wallet to be able to better manage our funds. And we build trust with the community. That's basically all we can do at this point.

Larger holding should also be on a hardware wallet, which won't ever leak private keys and verify transaction contents.
But Eternl can't help you apart from building trust month after month
