### ISSUE TITLE
asset vs collectible

### ISSUE THREAD

**Issue by huths0lo** [ccwalletio/tracker#62]
Will there be a way to designate assets vs collectibles?  If yes, we have registered cbTHC with the registry.  Would be awesome to have it display with 6 decimal places.  Token is 025146866af908340247fe4e9672d5ac7059f1e8534696b5f920c9e6.cbTHC

**Comment by mezuny** [comment]
Hi @huths0lo, I believe we are currently respecting the 'provided' amount of decimals, cbTHC also looks good in my wallet. We will close the Issue for now. Thanks for reaching out!

**Comment by Scitz0** [comment]
Just to add some clarification. Once token details/metadata is pulled, its locally cached in browser storage to save on loading time and reduce load on backend api's serving the data. If metadata is changed after this, you can manually refresh the data by pressing the refresh button in modal header next to token title.
