### ISSUE TITLE
Multiple addresses sent in a single transaction for CCVault

### ISSUE THREAD

**Issue by Hizairi** [ccwalletio/tracker#65]
Hi there, I am not from an IT background. I am here just as a supportive community member that would love to see Cardano network grows.

I would want to suggest CCVault to enable an option to send ADA to multiple wallet addresses. I have a number of ADA wallets currently staking and would love to be able to send ADA to my other wallets within ONE transaction. This saves transaction fees.

Thank you. Have a nice day.

**Comment by eddex** [comment]
Same request as #60, glad to see I'm not the only one who would like to have this feature!

**Comment by brouwerQ** [comment]
Same request!

**Comment by marcuspuchalla** [comment]
This feature has already been requested here https://github.com/ccwalletio/tracker/issues/60
