### ISSUE TITLE
Two issues with the browser extension

### ISSUE THREAD

**Issue by wout** [ccwalletio/tracker#66]
OS: elementary OS 6.1
Browser: Brave Version 1.34.80

**Issue 1**: Network switching using the bottom-right menu stopped working. I have to manually enter the network name in the URL. There are no errors in the console. When I click on the menu it appears and when I click on the network it disappears again, but nothing happens.

**Issue 2**: Wallets are shown as "not delegated", while they are.

![image](https://user-images.githubusercontent.com/107324/149652660-510622a6-3a24-41be-9366-76bc7273a4f3.png)

Both issues are only present in the browser extension, not in the web version. A temporary fix is to restart the browser, but after a while, it will break again.

**Comment by marcuspuchalla** [comment]
So are both points working when you start the browser, but they will not work after some time has passed?
We will try to set up your configuration and see what could cause the problem. Thanks for reporting.

**Comment by wout** [comment]
Yes, it only happens if the browser has been open for some time. I tend to reboot once to twice a month, and my Browser is not restarted very often either.

Restarting the browser always fixes the issue.

**Comment by mezuny** [comment]
Hi @wout, sorry for not getting back to you earlier. We have been very busy the past months. Such problems should not occur anymore, and if they do should be edge-cases. Please let us know if you've experienced it recently, we will close the issue for now.

**Comment by wout** [comment]
No worries, I understand. :)

I haven't noticed it lately, so all is well!
