### ISSUE TITLE
Add minimum amount Ada warning before staking

### ISSUE THREAD

**Issue by TheStophe** [ccwalletio/tracker#68]
Request to add a warning or prohibit one from staking one's wallet below the minimum Ada staking limit.

Background: After onboarding a friend to setup a new Cardano wallet on ccvault, he sent about 3 ada to it.  I showed him how to stake his ada, which turned out to be a 0.833 Ada internal transfer delegation fee, and then 2 Ada remaining.  The 2 Ada does not appear in his total wallet amount, although the transaction appears to have taken on the blockchain.  He's worried he lost his Ada.  Upon a little research, I figured it was probably because the minimum amount of Ada in a wallet to stake is 10 Ada (although I can't confirm the source in spec).  Perhaps consider adding a warning that your wallet amount is too low to stake, prohibit the action of staking, or display the 2 Ada in the wallet amount regardless but with a warning?  For onboarding a newcomer, this was concerning to him he thought he lost his 2 Ada.

**Comment by mplomin** [comment]
There is no minimum amount to stake.  Daedalus and other wallets suggest 10 as the minimum, but that is not mandatory.  As for the 2 Ada, that is not spendable while the wallet is staked.  Your friend will get his 2 Ada back when he de-registers his wallet and leaves all stakepools.

**Comment by TheStophe** [comment]
Looks like there's a 2 Ada min delegation deposit, and then a 0.17 Ada transaction fee, per answers on [Cardano Stake Exchange: What is the minimum amount of Ada needed to stake?](https://cardano.stackexchange.com/questions/6505/what-is-the-minimum-amount-of-ada-needed-to-stake).  Feel free to add a comment there if that's incorrect.

**Comment by mezuny** [comment]
Hey @ccgarant, agreed, we should give a more descriptive notification of what is required to stake your ADA. We've added it to our to-do list to address this 😄 Thanks for your suggestion
