### ISSUE TITLE
Feature Request: please add firefox browser support

### ISSUE THREAD

**Issue by Josef3110** [ccwalletio/tracker#69]
As the title says, I've only firefox - so please add support for this browser!

**Comment by Stefan566** [comment]
I wouls support that. Firefox has a higher market share than Brave and Opera, so why is it not supported?

**Comment by marcuspuchalla** [comment]
We understand the need for a Firefox extension and would also love to see CCVault as an extension there. As for now, we'll not be able to provide one in the foreseeable future. We will look into that again at a later stage.

_Background Information_: We already had an extension available for Firefox for a short amount of time. But it was removed by Firefox sometime later. The process of adding it again is much more complicated and time-consuming than for other browsers. We don't have the human resources to do this with our small team.
