### ISSUE TITLE
FR: Add "Typeahead" Functionality for Token Selection

### ISSUE THREAD

**Issue by Crypto2099** [ccwalletio/tracker#7]
The current display of native tokens when building a send transaction is pretty good, and I appreciate seeing both the Asset ID as well as the ASCII name of the token. However, in my experience "Drop Downs" are cumbersome to use when dealing with dozens if not hundreds of potential entries in the wallet.

I would recommend using a "Typeahead" functionality to the token selection input for the sake of user experience. It would be cool if we could search by Asset ID, ASCII token name, and potentially policy ID as well.

![image](https://user-images.githubusercontent.com/63186174/123685782-e7c6d080-d803-11eb-831e-3f1d0b789772.png)

**Comment by ccwalletio** [comment]
You can now filter by asset id or name.

**Comment by Crypto2099** [comment]
This looks good but leaves a weird artifact when a token has been selected

![image](https://user-images.githubusercontent.com/63186174/123700597-8a3b7f80-d815-11eb-89cd-047a812338db.png)

**Comment by Crypto2099** [comment]
Also a minor quality of life improvement here might be to have a "Send All"/sigma button on the amount field so I can click a button rather than having to type "1" for each NFT I'm sending.

**Comment by Scitz0** [comment]
Sigma button added and to be included in an upcoming release. The blue border/ring on the search field on focus is also fixed.
