### ISSUE TITLE
Need to educate delegators a bit more about multi-pooling / decentralization

### ISSUE THREAD

**Issue by hodlonaut** [ccwalletio/tracker#70]
Hello,

It might be a good idea to make the 'Pools of multi pool operations get a higher score penalty with each additional pool.' text in the Staking section bold and add to it a hyperlink to a useful educational resource about why there is a distinction being made between single pool and multi pool operators (https://cardano-community.github.io/support-faq/#/select-pool-to-delegate?id=number-of-pools-run-by-operator for example - and/or https://adapools.org/groups), or if those two aren't deemed to be appropriate perhaps I can conjure one up.

**Comment by marcuspuchalla** [comment]
Thank you for your contribution. We will discuss this internally and come back to it.

**Comment by hodlonaut** [comment]
Still waiting.

**Comment by mezuny** [comment]
@hodlonaut We have discussed and will look into ways to add a little more information. We do already prefer SPOs in our explorer. I think further explanation or in-depth information would be best left up to Cardano documentation
