### ISSUE TITLE
Locked out of the wallet. We should be able to reset the password with the passphrase!

### ISSUE THREAD

**Issue by Mit4Code** [ccwalletio/tracker#71]
Hi. It looks like I managed to do a typo or something when I've set my password for the wallet. I have tried quite a few times to guess it but I'm locked out. Now, one would think that it's not a big deal since it has the passphrase but I have tried to use the passphrase and CCvault says that I already have the wallet and it asks me the password. It is like the password now became the main security feature of the wallet and not the passphrase. This isn't the way how it should be. 

Obviously, I used the passphrase and I restored on another browser, or I can restore on another wallet like Daedalus and so on. The password is just a local and secondary security feature and it should not popup even after we use the passphrase, instead we should be able to set a new password.

I hope that this would be fixed because many people may forget the password counting on the fact that they took propper measures for their passphrase.

**Comment by marcuspuchalla** [comment]
As you mentioned, you can always restore the wallet from the passphrase. If CCVault tells you that a wallet already exists, you could clear the site's stored data and enter it again. But be aware that this will delete all wallets you created on that instance.

Setting the access password is a security feature. It will encrypt your wallet with this password. So after you set the password, no one can decrypt it without the password. So even if you enter the wallet phrase, we cannot decrypt the wallet with that.

But we probably could detect that you already have a wallet created with that seed phrase. And when we detect this wallet is locked, we might offer a way to delete this wallet and create a new one. We will discuss this and come back to this issue.

**Comment by Mit4Code** [comment]
The deletion of that particular locked wallet is exactly what is needed. By having the passphrase you actualy proofed that you own the wallet and this should allow it to be deleted and at the same time restored asking you to choose a new password to encrypt it.

**Comment by marcuspuchalla** [comment]
@Mit4Code, this feature is now available.
If you restore a wallet with a passphrase for a currently locked wallet, you will see this dialog and can recreate that wallet. Please notice that the settings for that wallet will also be reset.

If you have any other questions, feel free to comment here.

<img width="620" alt="Bildschirmfoto 2022-09-15 um 16 54 17" src="https://user-images.githubusercontent.com/89977979/190437109-7d58256a-3152-4b56-99d9-7becb209d63d.png">
