### ISSUE TITLE
Add ability to switch between networks to Settings menu

### ISSUE THREAD

**Issue by hodlonaut** [ccwalletio/tracker#73]
Currently the network switch is done via a small clickable text in bottom right corner of the screen.

A few users I've come across were unsure how to switch between testnet and mainnet, after looking in Settings section of the chrome extension. It might be worth considering adding the network toggle there as well and possibly prefixing the 'Tesnet' text in bottom right with 'Current Network:' label if there is room for that sort of thing.

**Comment by marcuspuchalla** [comment]
Thank you for that suggestion.

We might add a setting to the global settings page to see and change the current network.
I'll discuss this with the team and come back to it soon.
