### ISSUE TITLE
ccVault iOS won't read Nami wallet QR code

### ISSUE THREAD

**Issue by docter-tirrud** [ccwalletio/tracker#75]
I wanted to send ADA from iOS ccWallet.io to Mac Nami Wallet. I initiated the process on iPhone and went to enter receive address. I clicked the QR icon in the lower left, gave permission to use iPhone camera, and framed the Nami receive QR code in the iPhone camera window. No matter how I adjusted orientation the iPhone ccVault.io app would **not** recognize the QR code displayed by NamiWallet in Brave on MacOS X (details of all versions below).

QR code displayed by Nami:

![image](https://user-images.githubusercontent.com/92059696/150148771-183f48ac-dbc8-4e83-a361-571253e4585a.png)

- iOS version: 15.2.1
- ccVault.io iOS version: 1.3.7
- MacOS Version: 12.1
- Brave version: 1.34.80
- NamiWallet version: 3.10

**Comment by marcuspuchalla** [comment]
Thank you for the report. I can confirm that our current implementation seems to have problems with that code type.
We will look into this asap.

**Comment by marcuspuchalla** [comment]
@docter-tirrud I looked at this issue again and found that the QR code will be detected fine when you use "Light mode" in Nami. When using the dark mode, the QR code also gets inverted, which per best practice for QR codes, should not be done, as some scanners have a problem detecting such codes. We cannot change our QR code scanner at the moment, so I suggest you switch to the light mode when scanning those codes. 

For any further questions, feel free to comment on this issue. I'll, for now, close this one.
