### ISSUE TITLE
Change token collection chevron direction from down/up to right/down

### ISSUE THREAD

**Issue by mplomin** [ccwalletio/tracker#76]
This may be an incredibly minor change request, but bear with me.  

When you own more than 2 tokens from one collection, the default is a "collapsed" state of the view, with a downward facing chevron / arrow. 

Then, when you click on the down chevron, the rest of the collection is revealed, and the image changes to an up chevron.  

In most places, you will see collapsed views with a right-facing chevron, and then expanded views with a downward facing chevron.

**Comment by mezuny** [comment]
Hi @mplomin, thanks for this suggestion, you're completely right! It bothered me too, and it should be fixed in most places for next release by the end of (hopefully) this week.
