### ISSUE TITLE
Short-term QR Retention after voting

### ISSUE THREAD

**Issue by madprogramer** [ccwalletio/tracker#77]
Mis-clicking another tab after voting, drops the QR code and sends the user back to the Catalyst Registration screen. 
![image](https://user-images.githubusercontent.com/3719664/150371232-20651567-1368-4d62-8520-4681f772b7c0.png)

Since voting registration incurs a registration transaction fee, it might be nice to have some short-term retention (to give the user time to save their QR code) before losing it.

**Comment by TheStophe** [comment]
Agree.  It's really easy to just click finish after signing the transaction, when doing multiple accounts.  Request to add:
- Bigger Save QR Image Button (or just do it automatically)
- AND add more interlocks, asking if you sure you saved your QR code, or asking to check a box.
- Short term QR code retention best if accidentally click Finish without saving. I actually did it in Fund7 and again in Fund8.

**Comment by Scitz0** [comment]
There are big changes on their way for voting, not only for Eternl but all wallets. You will be able to recover voting keys from wallet and not using one time throw-away keys like now. Voting delegation and more.

This will come in the coming months. We are working with IOG and the other wallet teams on this. Its very hard to predict a timeframe at this point though.

**Comment by TheStophe** [comment]
Sounds good, thank you.
