### ISSUE TITLE
Feature request: saving signed transaction instead of sending it

### ISSUE THREAD

**Issue by brouwerQ** [ccwalletio/tracker#79]
The wallet has a good dapp connector and a lot of options (and more will become available), so it's a excellent tool to construct transactions. However, when load is high, it's difficult to get transactions through. I would really like an option to sign and save instead of sign and send, so that I can try to send the tx through my own node.

**Comment by marcuspuchalla** [comment]
This is already implemented in the current version, please have a look and feel free if you have any suggestions.
