### ISSUE TITLE
Usability Issue: Strange Refresh Behavior

### ISSUE THREAD

**Issue by Crypto2099** [ccwalletio/tracker#8]
If you go to the "Send" pane and then refresh the page (F5) the wallet will reload and you can select the wallet and it will default to the summary view but the "Send" tab is still highlighted/selected. Clicking on the "Send" tab will not open the send transaction interface until you click onto one of the other tabs and then back to send.

![image](https://user-images.githubusercontent.com/63186174/123697813-311e1c80-d812-11eb-9f39-a4a5c5fd60ed.png)

**Comment by MarcelKlammer** [comment]
Navigation should be fine now, even when switching wallets using the arrow in the top left.

**Comment by ccwalletio** [comment]
Switching wallets will result in switching to summary for unlocked wallets and settings for locked wallets.
