### ISSUE TITLE
add support for non-UTF8 characters

### ISSUE THREAD

**Issue by angelstakepool** [ccwalletio/tracker#86]
playing with testnet minswap, It seems that ccvault does not support non-UTF8 characters

![lq](https://user-images.githubusercontent.com/60072039/151338525-77828360-b28c-4634-8f55-dd0e8158fb76.jpg)

**Comment by mezuny** [comment]
Hi @angelstakepool, we have added a change a while back to specifically take care of this. Thanks for the suggestion!
