### ISSUE TITLE
Feature request: enable renaming of the sub accounts

### ISSUE THREAD

**Issue by Pr0phecy77** [ccwalletio/tracker#87]
Right now, the default naming of the extra accounts you can create is Account 1, Account 2 etc. Would be nice to be able to rename these accounts.

**Comment by QCPOLstakepool** [comment]
This, please :)

**Comment by EGMSSE** [comment]
would love to see this feature

**Comment by mezuny** [comment]
Hey @Pr0phecy77, @QCPOLstakepool  and @EGMSSE. This is on our to do for sure! I expect we will add this relatively soon (hopefully within a month). Thank you for your feedback!
