### ISSUE TITLE
Congestion: Pending transaction disappears / error

### ISSUE THREAD

**Issue by MadOrkestra** [ccwalletio/tracker#88]
This happend to me several times now, so I'll try to put this out here to check: You send one transaction which shows as pending for a long while due to the current congestion, then disappears but does not show in the transactions (not on chain yet or not being synced back to the transactions view right away). If you try to send another transaction at this point (even to a different address), you'll get an error like:

```
Failed
400:
0: {"consumed":{"coins":0,"assets":{}},"produced":{"coins":151764978,"assets":{}}}
1: [{"txId":"59af908662844ad5979813d1480dfe597212dce5d1224dd1e37aa485092aea68","index":1}] 
```

However: The first transaction is being processed and will show up in the transaction much later, but does not show anywhere for a moment (or a while, depending on congestion). No pending alert is shown. So you _think_ its lost somewhere, while it is in fact being processed.

**Comment by mezuny** [comment]
Hey @MadOrkestra, sorry for the late reply. We're currently going through our backlog of issues on the git. At this point, this shouldn't happen anymore with both additional server capacity and the addition of the pending tab. Thank you for reaching out!
