### ISSUE TITLE
Feature request: Use your own Cardano Node 

### ISSUE THREAD

**Issue by yronin** [ccwalletio/tracker#89]
Hello,

it would be lovely if we could configure the use of our own Cardano Full Node in ccvault.

Kind regards

**Comment by jarkkosyrjala** [comment]
For reference, this is how the feature is implemented in Nami:

https://github.com/Berry-Pool/nami-wallet/commit/a1ea1e4462f6beef45348e4ca98c9d4ff9666882
And additional fix for error handling: https://github.com/Berry-Pool/nami-wallet/commit/7677eb91e083c25c1731973b2c373e3105de939b

**Comment by kastik** [comment]
The extension already support this under App Preferences > Custom Submit API Endpoint.

**Comment by mezuny** [comment]
Thanks for your suggestion, but we are currently not planning to add such functionalities in the future. Custom submit endpoint has been added at this point.
