### ISSUE TITLE
Fearure request: custom submit-api url

### ISSUE THREAD

**Issue by safanaj** [ccwalletio/tracker#90]
This could be a subset of #89 just for the tx submission functionality. Similar to what Nami wallet implemented by day zero would be nice to have in the settings section the possibility to specify a cardano-submit-api URL, and would be also much great allow optionally to provide a client certificate to use making POST requests to the submit api url. In this way each SPO (or just anyone running a relay/local node) can provide this service endpoint, decreasing the pressure from the ccvault infra. From a SPO perspective the client certificate could aim to implement authentication/authorization distributing different certificates to his own delegators.

**Comment by brouwerQ** [comment]
Let's start with just the custom submit api URL... I would really like that too.

**Comment by yronin** [comment]
Yes please! I would love this feature.

**Comment by dreday966** [comment]
This feature will make ccvault.io be the only option.

**Comment by kastik** [comment]
The extension already support this under App Preferences > Custom Submit API Endpoint.

**Comment by marcuspuchalla** [comment]
As @kastik mentioned, this is already supported by the extension.
