### ISSUE TITLE
Feature Request: UTXO management

### ISSUE THREAD

**Issue by kaskjabhdlf** [ccwalletio/tracker#92]
This feature is taken directly from Electrum BTC.

I'd like to be able to choose which UTXOs I want to spend from and have the ability to lock others. This is a privacy feature for wallets that are not staked. Single UTXO spends prevent identifying public wallets that are associated with each other by private key. Having just one UTXO selected while using 'send all' would optimize the fee to spend the entire UTXO without change. Users will be able to lock a UTXO with tokens they have no intention of spending to prevent any accidental send. This also provides a tax benefit, allowing users to differentiate between long and short term capital gains by UTXO age.

**Comment by marcuspuchalla** [comment]
Thanks for the suggestion. We will discuss this internally and might implement it in the future.

**Comment by marcuspuchalla** [comment]
Hello @kaskjabhdlf,

We've implemented the feature, and its already usable in the wallet.

You can now lock UTXO in the UTXO List view in your wallet. There is a little lock on the left of a UTXO.
This will prevent the UTXO from being included in a transaction. 

On the Send page, you can also see how much ADA are locked by those locked UTXOs (see: "By locked UTxOs")

If you have any more suggestions or feel that something is missing, please feel free to open this issue again or open a new one.

Best regards
Marcus
