### ISSUE TITLE
Feature Request: Import/export transaction as file

### ISSUE THREAD

**Issue by kaskjabhdlf** [ccwalletio/tracker#93]
This feature is taken directly from Electrum BTC

I'm not sure how watch-only wallets (master public keys - xpub.. in BTC land) work on Cardano, or if they even do. Their existence is required for much of this feature to work.

Without the ability to interact with smart contracts using a hardware wallet, users are forced to create a 'hot' wallet. This is a massive security vulnerability. I'd like to be able to take ccvault to an offline computer or non persistent environment to generate a seed phrase and only interact with the key there.

Using an online watch-only version of my wallet I can build my transaction and export it, unsigned, to file. Bring the file to offline environment where it is signed and exported as file. Bring back to ccvault online environment where it is submitted to mempool, or bring to my own node to be submitted.

The ability to export to file would help with the current congestion issues by allowing users to use their own mempool instead of ccvault's shared pool.

The ability to import file will allow users to interact with their HW keys in more ways. Pool owners can witness/sign pool transactions among other required signatures from HW keys.

**Comment by mezuny** [comment]
Hi @kaskjabhdlf, thank you for this suggestion. Using a HW wallet however doesn't create a hot wallet, it basically views a public key and communicates with the ledger/trezor what it wants to do. We do at this point allow for users to use their own custom endpoint, so this shouldn't be a problem either. 

After reading the above, do you still think something should be changed? Let us know
