### ISSUE TITLE
Feature Request: Add note to transaction

### ISSUE THREAD

**Issue by kaskjabhdlf** [ccwalletio/tracker#94]
Within my transaction history it would be nice to be able to make a note on transactions.

"bob payed me for his half of the dinner bill"

This would only be a local wallet note and not reside with the seed phrase out be stored on chain.

**Comment by mezuny** [comment]
Hi @kaskjabhdlf, this would add some challenges, as local would truly be local. We do not save any info from our users, so wouldn't have any way to synchronize this between wallets. Restoring your wallet would also for example mean losing these notes.

**Comment by Scitz0** [comment]
Feature request added on internal todo. It just needs to be made clear that its a local note and not synced. Any browser storage clearing, manual or automatic by browser, or indexeddb corruption will make notes unrecoverable. Exact details for implementation not thought through but most likely will be part of wallet json so one could backup/sync notes this way.
