### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by turtlelord-17** [ccwalletio/tracker#95]
can you guys please add a dark mode. Wallet so white it hurts my eyes.

**Comment by TensorsWillFlow** [comment]
ccvault is hands down the best cardano wallet at the moment, but... my.... eyes 🤣

**Comment by mezuny** [comment]
Hi @turtlelord-17 and @TensorsWillFlow, thanks for this suggestion! We've added this a few updates ago, I hope you have been enjoying the darkmode we created. If you have any feedback, do let us know!
