### ISSUE TITLE
Why can't I connect to the mainnet?

### ISSUE THREAD

**Issue by SunflowerHLim** [ccwalletio/tracker#98]
![image](https://user-images.githubusercontent.com/100850628/156573750-c24ee808-f88a-4de6-b327-1c3c378a9525.png)

It has a good Internet connection, but it is said that it cannot be connected. Please solve the problem.

**Comment by mezuny** [comment]
Hey @SunflowerHLim, I hope at this point you have been able to either join our Telegram/Discord or to resolve this. It might've been an outage or epoch rollover at the time. As you might notice, we're a bit behind on replying. Sorry about that!
